apiVersion: v1
kind: Service
metadata:
  name: runbook-agent
  namespace: default
  labels:
    app: runbook-agent
spec:
  type: LoadBalancer
  selector:
    app: runbook-agent
  ports:
    - name: metrics
      port: 8001
      targetPort: 8000
